version: "3"
services:
  backend:
    image: node:latest
    command: npm run start
    network_mode: "host"
    # ports:
    #   - "3001:3001"
    logging:
      driver: "json-file"
    working_dir: /usr/src/harity/backend
    volumes:
      - ./backend:/usr/src/harity/backend
  frontend:
    image: node:latest
    command: npm run start
    network_mode: "host"
    volumes:
      - ./frontend:/usr/src/harity/frontend
    working_dir: /usr/src/harity/frontend
  mongo:
    image: mongo:latest
    network_mode: "host"
    # ports:
    #   - "27017:27017"
    logging:
      driver: "json-file"
    volumes:
      - ./backend/data:/data/db
      - /backend/log/mongo:/var/log/mongodb
